# Generated by Django 6.0 on 2025-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data', models.DateField()),
                ('autor', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TarefaModel',
        ),
    ]
